// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1YIleuPnJ-b-UnIoAi19h-Jqlyoc5Z9E',
    appId: '1:675353231957:web:483401784d8dcbef528adc',
    messagingSenderId: '675353231957',
    projectId: 'travelbuddy-53dd8',
    authDomain: 'travelbuddy-53dd8.firebaseapp.com',
    storageBucket: 'travelbuddy-53dd8.firebasestorage.app',
    measurementId: 'G-TZ7KV6YHGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaN9FuacSgDT1-Spf33-DFd7-MC72Spkg',
    appId: '1:675353231957:android:17da96978c15ac6b528adc',
    messagingSenderId: '675353231957',
    projectId: 'travelbuddy-53dd8',
    storageBucket: 'travelbuddy-53dd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxCGFcZa5KXmY39IuzcnhZMJeAAsuWctU',
    appId: '1:675353231957:ios:c5cb02c70da05f1b528adc',
    messagingSenderId: '675353231957',
    projectId: 'travelbuddy-53dd8',
    storageBucket: 'travelbuddy-53dd8.firebasestorage.app',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxCGFcZa5KXmY39IuzcnhZMJeAAsuWctU',
    appId: '1:675353231957:ios:c5cb02c70da05f1b528adc',
    messagingSenderId: '675353231957',
    projectId: 'travelbuddy-53dd8',
    storageBucket: 'travelbuddy-53dd8.firebasestorage.app',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1YIleuPnJ-b-UnIoAi19h-Jqlyoc5Z9E',
    appId: '1:675353231957:web:02f2d008516d74af528adc',
    messagingSenderId: '675353231957',
    projectId: 'travelbuddy-53dd8',
    authDomain: 'travelbuddy-53dd8.firebaseapp.com',
    storageBucket: 'travelbuddy-53dd8.firebasestorage.app',
    measurementId: 'G-3SLNLL78JC',
  );
}
